services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Password1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnet

  api:
    build:
      context: .
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=PontoDB;User Id=sa;Password=YourStrong@Password1;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - appnet

  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   ports:
  #     - "4200:80"
  #   networks:
  #     - appnet

networks:
  appnet:
